name: pylegomac
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py36_0
- conda-forge::chardet=3.0.2=py36_1
- conda-forge::click=6.7=py36_0
- conda-forge::idna=2.5=py36_0
- conda-forge::ncurses=5.9=10
- conda-forge::openssl=1.0.2l=0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::python=3.6.1=3
- conda-forge::pyyaml=3.12=py36_1
- conda-forge::readline=6.2=0
- conda-forge::requests=2.18.1=py36_0
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::urllib3=1.21.1=py36_0
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zlib=1.2.11=0
