---
pigpiod_host: 'localhost'
pigpiod_port: 8888
host: 'localhost'
port: 8080
username: 'username'
password: 'secret'
jwt_secret: 'secret'
jwt_algorithm: 'HS256'
# 3600 * 24 * 7 (1 week)
jwt_exp_delta_seconds: 604800
timezone: 'Europe/Stockholm'
